function val=rrrToRreBoundary(xi,delta,gamma_I,gamma_II,M_I,M_II)
%Computes RRE<->RRR boundary function
val=(((xi-1)*(gamma_I+1))...
    /(2*gamma_I)+1)*((xi^2*(gamma_I+1)+gamma_I-1)...
    /(2*sin(delta)^2)-xi+1)^2*...
    ((-(xi-1)*(gamma_II+1))/(2*gamma_II)+...
    (M_II*(xi^2*(gamma_I+1)+gamma_I-1))...
    /(2*M_I*sin(delta)^2*gamma_II)-1)-...
    ((M_II*(xi^2*(gamma_I+1)+gamma_I-1))/...
    (2*M_I*sin(delta)^2)-xi+1)^2*((xi^2*(gamma_I+1)...
    +gamma_I-1)/(2*sin(delta)^2*gamma_I)-((xi-1)...
    *(gamma_I+1))/(2*gamma_I)-1)*(((xi-1)...
    *(gamma_II+1))/(2*gamma_II)+1);
end